GET http://localhost:8080/bloom/idExists?id=10
#Accept: application/json
#
####


GET http://localhost:8080/bloom/idExists?id=11
Accept: application/json

###


GET http://localhost:8080/bloom/redisIdAdd?id=20
Accept: application/json

###


GET http://localhost:8080/bloom/redisIdExist?id=15
Accept: application/json

###



GET http://localhost:8080/redis/secsale?uid=1&skuId=1
Accept: application/json

###

